import { IRowOrderDataProps } from "@/types";
export const rowOrderData: IRowOrderDataProps[] = [
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 13,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 113,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 153,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 213,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    id: 123,
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
  {
    name: 'Nguyễn Văn Kiệt',
    address: 'UOA Tower Quận 7',
    id: 123,
    orders: 'Nước ép trái cây',
    date: '25.1.2023',
    status: 'Đang giao hàng',
    action: '',
  },
];
